### ISSUE TITLE
Auth Code creation widged is hidden if there are too many flights

### ISSUE THREAD

**Issue by sidney-pauly** [AberdeenRSS/FlightManagementClient#18]
At the top of the flights there should be a widged to create new auth codes to be used. It gets hidden if there are too many flights: 
![image](https://github.com/AberdeenRSS/FlightManagementClient/assets/44103563/82d99e37-0332-4d5e-8b26-646ebcbdd830)

**Comment by alanjsfleming** [comment]
https://github.com/AberdeenRSS/FlightManagementClient/pull/39
